[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
flutter_rust_bridge = "1.72.1"
p224 = "^0.13.1"
getrandom = "0.2"

[features]
default = ["p224/ecdh", "getrandom/js"]

[profile.release]
opt-level = 3
lto = true


