// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

abstract class Native {
  Future<Uint8List> ecdh(
      {required Uint8List publicKeyBlob,
      required Uint8List privateKey,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEcdhConstMeta;
}

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<Uint8List> ecdh(
      {required Uint8List publicKeyBlob,
      required Uint8List privateKey,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(publicKeyBlob);
    var arg1 = _platform.api2wire_uint_8_list(privateKey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ecdh(port_, arg0, arg1),
      parseSuccessData: _wire2api_uint_8_list,
      parseErrorData: null,
      constMeta: kEcdhConstMeta,
      argValues: [publicKeyBlob, privateKey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEcdhConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ecdh",
        argNames: ["publicKeyBlob", "privateKey"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
