name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/checkout@v3
    - run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
    - run: cargo install cargo-ndk
    - run: flutter pub get
    - run: flutter build apk --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ./build/app/outputs/flutter-apk/app-release.apk
