name: Release (Android, Web)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/checkout@v3
    - run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
    - run: cargo install cargo-ndk
    - run: flutter pub get
    - run: flutter build apk --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ./build/app/outputs/flutter-apk/app-release.apk
    - run: rustup override set nightly
    - run: rustup component add rust-src
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install wasm-pack
    - run: wasm-pack build -t no-modules -d ./web/pkg --no-typescript --out-name native native -- -Z build-std=std,panic_abort
    - run: flutter build web --release --dart-define=FLUTTER_WEB_CANVASKIT_URL=https://cdn.jsdelivr.net/npm/canvaskit-wasm/bin/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: ./build/web

